### ISSUE TITLE
【文章推荐】理解 Stack Trace

### ISSUE THREAD

**Issue by gaufung** [DotNETWeekly-io/DotNetWeekly#722]
https://blog.elmah.io/understanding-net-stack-traces-a-guide-for-developers/

**Comment by gaufung** [comment]
![image](https://github.com/user-attachments/assets/7ce9fbd7-2b8a-4bfe-bb9a-b2ce1cade520)

理解 C# 代码中的异常调用栈（Stack Trace) 对于我们 debug 非常有帮助， `C#` 中有如下几种异常调用栈信息

- Stack Trace

```txt
System.NullReferenceException: Object reference not set to an instance of an object.
   at ConsoleApp.Program.MethodA() in C:\projects\ConsoleApp\Program.cs:line 20
   at ConsoleApp.Program.Main(String[] args) in C:\projects\ConsoleApp\Program.cs:line 10
```

调用栈的第一行指出了抛异常的内容，是 `NullReferenceException`, 下面紧接着是调用的反顺序。不过值得注意的是，它每一行都有三个空格。

- Inner Exception Stack Trace

当你的代码抛出异常后，被 `catch` 语句捕获后，然后重新的抛出新的异常，可以原本的异常将设置为最外面的异常的 `InnerException` 属性

```txt
Unhandled exception. System.ApplicationException: application error
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Program.<Main>$(String[] args) in C:\Users\fenga\tizan\codebase\episodes\exceptiondemo\Program.cs:line 6
   --- End of inner exception stack trace ---
   at Program.<Main>$(String[] args) in C:\Users\fenga\tizan\codebase\episodes\exceptiondemo\Program.cs:line 10
```

这里用 ` --->` 指出下面的异常是来自 `InnerException` 而 ` --- End of inner exception stack trace --` 表示 `InnerException` 已经结束，下面的的内容就是原本最外面异常的调用栈。

- Aggregated Exception Stack Trace

`Aggregated Exception` 用来封装多个异常，通常发生在并行或者异步中代码代码中

```txt
System.AggregateException: One or more errors occurred. (One of the identified items was in an invalid format.) (Object reference not set to an instance of an object.)
 ---> System.FormatException: One of the identified items was in an invalid format.
   at ConsoleApp.A.X() in C:\projects\ConsoleApp\A.cs:line 13
   at Program.<Main>$(String[] args) in C:\projects\ConsoleApp\Program.cs:line 9
   --- End of inner exception stack trace ---
 ---> (Inner Exception #1) System.NullReferenceException: Object reference not set to an instance of an object.
   at ConsoleApp.B.Y() in C:\projects\ConsoleApp\A.cs:line 21
   at Program.<Main>$(String[] args) in C:\projects\ConsoleApp\Program.cs:line 18
<---
```

第一行的 `AggregateExcpetion` 用括号标记出每个异常的 `Message`, 在这里用两个异常。接着下面的 `--->` 开头的部分，标记出每个异常的调用栈信息。

- Fattened Stack Trace

在异步代码中，有时候程序运行在不同的代码片段中。

```txt
Azure.Messaging.ServiceBus.ServiceBusException: The lock supplied is invalid. Either the lock expired, or the message has already been removed from the queue, or was received by a different receiver instance. (MessageLockLost). For troubleshooting information, see https://aka.ms/azsdk/net/servicebus/exceptions/troubleshoot.
   at Azure.Messaging.ServiceBus.Amqp.AmqpReceiver.ThrowLockLostException()
   at Azure.Messaging.ServiceBus.Amqp.AmqpReceiver.DisposeMessageAsync(Guid lockToken, Outcome outcome, TimeSpan timeout)
   at Azure.Messaging.ServiceBus.Amqp.AmqpReceiver.CompleteInternalAsync(Guid lockToken, TimeSpan timeout)
   at Azure.Messaging.ServiceBus.Amqp.AmqpReceiver.<>c.<<CompleteAsync>b__43_0>d.MoveNext()
--- End of stack trace from previous location ---
   at Azure.Messaging.ServiceBus.ServiceBusRetryPolicy.<>c__22`1.<<RunOperation>b__22_0>d.MoveNext()
--- End of stack trace from previous location ---
   at Azure.Messaging.ServiceBus.ServiceBusRetryPolicy.RunOperation[T1,TResult](Func`4 operation, T1 t1, TransportConnectionScope scope, CancellationToken cancellationToken, Boolean logRetriesAsVerbose)
   at Azure.Messaging.ServiceBus.ServiceBusRetryPolicy.RunOperation[T1](Func`4 operation, T1 t1, TransportConnectionScope scope, CancellationToken cancellationToken)
   at Azure.Messaging.ServiceBus.Amqp.AmqpReceiver.CompleteAsync(Guid lockToken, CancellationToken cancellationToken)
   at Azure.Messaging.ServiceBus.ServiceBusReceiver.CompleteMessageAsync(ServiceBusReceivedMessage message, CancellationToken cancellationToken)
   at Azure.Messaging.ServiceBus.ReceiverManager.ProcessOneMessage(ServiceBusReceivedMessage triggerMessage, CancellationToken cancellationToken)
```

在这里使用 ` --- End of stack trace from previous location ---` 作为分隔符，表明代码执行到这里，然后去其他地方。这个经常发生了 `await` 结束后，继续执行面的代码。
